data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/SceneFlow/sceneflow_finalpass_train.txt
  val_list: datasets/SceneFlow/sceneflow_finalpass_test.txt
  test_list: datasets/SceneFlow/sceneflow_finalpass_test.txt
  num_workers: 4
  train_batch_size: 2
  val_batch_size: 10
  pin_memory: true
  shuffle: true

  batch_uniform: false
  #  random_type: range
  #  w_range: [ 0.5, 2.0 ]
  #  h_range: [ 0.5, 2.0 ]
  #  random_type: choice
  #  h_range: [ 256, 288, 320, 352 ]
  #  w_range: [ 480, 512, 544, 576 ]

  transform:
    train:
      - type: FlowAugmentor
        size: [ 320, 736 ]
        min_scale: 0.2
        max_scale: 0.5
        do_flip: false
        h_flip_prob: 0.5
        v_flip_prob: 0.1
#      - type: NormalizeImage
#        mean: [ 0.485, 0.456, 0.406 ]
#        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: TestCrop
        size: [ 512, 960 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
#      - type: NormalizeImage
#        mean: [ 0.485, 0.456, 0.406 ]
#        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: IGEV
  find_unused_parameters: true

  base_config:
    max_disp: 192


loss_cfg:
  # This model uses the user-defined loss function.


trainer_cfg:
  save_name: igev_sf
  total_epoch: 100 # remember to give a large number here if using max_iter to control the training process
  max_iter: 200100
  restore_hint: 0
  log_iter: 10 # iter
  save_every: 1 # epoch
  val_every: 1 # epoch
  amp: true
  sync_bn: true
  fix_bn: true
  init_parameters: false

  optimizer_cfg:
    solver: AdamW
    lr: 0.0002
    weight_decay: 0.00001
    eps: 0.00000001

  scheduler_cfg:
    scheduler: OneCycleLR
    max_lr: 0.0002
    total_steps: 200100
    pct_start: 0.01
    cycle_momentum: False
    anneal_strategy: linear
    on_epoch: false
#    warmup:
#      warmup_steps: 2000

  evaluator_cfg:
    metric:
      - d1_all
      - epe
      - thres_1
      - thres_2
      - thres_3

  clip_grad_cfg:
    type: value
    clip_value: 1.0
