data_cfg:
  name: KITTI2015
  root: data/kitti15
  train_list: datasets/kitti15/kitti15_train165.txt
  val_list: datasets/kitti15/kitti15_val35.txt
  test_list: datasets/kitti15/kitti15_test.txt
  num_workers: 4

  transform:
    train:
      size: [ 256, 512 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]
    test:
      size: [ 544, 960 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: LacGwcNet
  base_config:
    max_disp: 192


optimizer_cfg:
  solver: AdamW
  lr: 0.0001
  betas: [ 0.9, 0.999 ]


loss_cfg:
  # This model uses the user-defined loss function.

scheduler_cfg:
  scheduler: MultiStepLR
  gamma: 0.1
  milestones:
    - 75000


trainer_cfg:
  save_name: LacGwcNet_kitti15_finetune
  restore_hint: output/SceneFlow/LacGwcNet/LacGwcNet_SceneFlow/checkpoints/LacGwcNet_SceneFlow-21800.pt
  restore_ckpt_strict: true
  log_iter: 1
  with_test: true
  enable_float16: false
  sync_BN: true
  save_iter: 200
  total_iter: 150000
  total_epoch: 20000
  optimizer_reset: true
  scheduler_reset: true
  sampler:
    # type: BasicStereoSampler
    batch_shuffle: true
    batch_size: 1


evaluator_cfg:
  eval_func: OpenStereoEvaluator
  save_name: LacGwcNet_kitti15_finetune
  restore_hint: output/SceneFlow/LacGwcNet/LacGwcNet_SceneFlow/checkpoints/LacGwcNet_SceneFlow-21800.pt
  show_progress_bar: true
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  restore_ckpt_strict: true
  enable_float16: false
  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 1
