data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/sceneflow/sceneflow_cleanpass_train.txt
  val_list: datasets/sceneflow/sceneflow_cleanpass_test.txt
  test_list: datasets/sceneflow/sceneflow_cleanpass_test.txt
  num_workers: 8

  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      #- type: RandomHorizontalFlip
      #  prob: 0.5
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: StereoPad
        size: [ 544, 960 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: LacGwcNet
  #  find_unused_parameters: true
  base_config:
    max_disp: 192

loss_cfg:
# This model uses the user-defined loss function.


optimizer_cfg:
  solver: RMSprop
  lr: 0.001


scheduler_cfg:
  scheduler: MultiStepLR
  gamma: 0.1
  milestones:
    - 89000
  warmup:
    type: LinearWarmup
    warmup_period: 100


trainer_cfg:
  save_name: LacGwcNet_SceneFlow
  restore_hint: 1
  restore_ckpt_strict: true
  log_iter: 10
  with_test: true
  enable_float16: false
  sync_BN: false
  save_iter: 9000
  total_iter: 150000
  total_epoch: 20
  optimizer_reset: false
  scheduler_reset: false
  sampler:
    # type: BasicStereoSampler
    batch_shuffle: true
    batch_size: 4


evaluator_cfg:
  eval_func: OpenStereoEvaluator
  save_name: LacGwcNet_SceneFlow
  restore_hint: 0
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  restore_ckpt_strict: true
  enable_float16: false
  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 4
