data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/sceneflow/train.txt
  val_list: datasets/sceneflow/debug_val.txt
  test_list: datasets/sceneflow/test.txt
  num_workers: 4

  transform:
    train:
      size: [ 256, 512 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]
    test:
      size: [ 544, 960 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: PSMNet

  base_config:
    max_disp: 192

  # Backbone
  backbone_cfg:
    type: PSMNet

  # VolumeCostProcessor
  cost_processor_cfg:
    type: PSMCostProcessor

  # DispProcessor
  disp_processor_cfg:
    type: PSMDispProcessor


optimizer_cfg:
  solver: RMSprop
  lr: 0.001

loss_cfg:
  - log_prefix: disp
    loss_term_weight: 1
    type: Weighted_Smooth_l1_Loss
    weights: [ 0.5, 0.7, 1.0 ]


scheduler_cfg:
  scheduler: MultiStepLR
  gamma: 0
  milestones: # Learning Rate Reduction at each milestones
    - 25000

trainer_cfg:
  save_name: PSMNet_SceneFlow
  restore_hint: 0
  restore_ckpt_strict: true
  log_iter: 1
  with_test: true
  enable_float16: false
  save_iter: 2500
  sync_BN: true
  total_iter: 20000
  total_epoch: 20
  optimizer_reset: false
  scheduler_reset: false
  sampler:
    # type: DistributedSampler
    batch_shuffle: true
    batch_size: 1


evaluator_cfg:
  save_name: PSMNet_SceneFlow
  eval_func: OpenStereoEvaluator
  restore_hint: 0
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  enable_float16: false
  restore_ckpt_strict: true
  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 1
