
data_cfg:
  name: KITTI2015
  root: /mnt/cfs/algorithm/public_data/stereo/datasets/KITTI
  train_list: datasets/KITTI15/kitti15_train165.txt
  val_list: datasets/KITTI15/kitti15_val35.txt
  test_list: datasets/KITTI15/kitti15_test.txt
  num_workers: 8
  train_batch_size: 4
  val_batch_size: 1
  pin_memory: true
  shuffle: true

  batch_uniform: true
  random_type: choice
  h_range: [ 192, 256, 320 ]
  w_range: [ 448, 512, 576 ]

  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    val:
      - type: CropOrPad
        size: [ 384, 1280]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: DivisiblePad
        by: 16
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: FADNet
  find_unused_parameters: false

  base_config:
    max_disp: 192
  

  # Backbone
  backbone_cfg:
    type: FadnetBackbone
    resBlock: true
    maxdisp: 192
    input_channel: 3
    encoder_ratio: 16
    decoder_ratio: 16
    
  # VolumeCostProcessor
  cost_processor_cfg:
    type: FADAggregator
    resBlock: true
    maxdisp: 192
    input_channel: 3
    encoder_ratio: 16
    decoder_ratio: 16

  # DispProcessor
  disp_processor_cfg:
    type: DispNetRes
    in_planes: 11
    resBlock: true
    encoder_ratio: 16
    decoder_ratio: 16




loss_cfg:
  - log_prefix: dispnetc_flows
    type: MultiScaleLoss
    loss_term_weight: 1
    scales: 7
    downscale: 1
    weights: [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
    loss: L1
    maxdisp: 192
    mask: false
    

  - log_prefix: dispnetres_flows
    type: MultiScaleLoss
    loss_term_weight: 1
    scales: 7
    downscale: 1
    weights: [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
    loss: L1
    maxdisp: 192
    mask: false
    


trainer_cfg:
  save_name: Fadnet_SceneFlow_g8b96_lamb0004
  total_round: 1
  total_epoch: [2400]
  restore_hint: "/mnt/cfs/algorithm/youmin.zhang/output/SceneFlow/FADNet/Fadnet_SceneFlow_g8b96_lamb0004/checkpoints/Fadnet_SceneFlow_g8b96_lamb0004-33300.pt"
  optimizer_reset: false
  scheduler_reset: false
  warmup_reset: false
  log_iter: 1 # iter
  save_every: 100 # epoch
  val_every: 50 # epoch
  amp: false
  sync_bn: true
  fix_bn: false
  init_parameters: false

  optimizer_cfg:
    solver: lamb
    lr: 0.001

  
  scheduler_cfg:
    scheduler: MultiStepLR
    gamma: 0.5
    milestones: [ 300,500,600 ]
    warmup:
      warmup_steps: 100

  evaluator_cfg:
    metric:
      - d1_all
      - epe
      - thres_1
      - thres_2
      - thres_3

