data_cfg:
  name: DrivingStereo
  root: data/DrivingStereo
  train_list: datasets/DrivingStereo/driving_stereo_train.txt
  val_list: datasets/DrivingStereo/driving_stereo_half_test.txt
  test_list: datasets/DrivingStereo/driving_stereo_half_test.txt
  num_workers: 4

  batch_uniform: false
  #  random_type: range
  #  w_range: [ 0.5, 2.0 ]
  #  h_range: [ 0.5, 2.0 ]
  #  random_type: choice
  #  h_range: [ 256, 288, 320, 352 ]
  #  w_range: [ 480, 512, 544, 576 ]

  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      #- type: RandomHorizontalFlip
      #  prob: 0.5
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: StereoPad
        size: [ 540, 960 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: CoExNet
  find_unused_parameters: true

  base_config:
    max_disp: 192


loss_cfg:
  - log_prefix: disp
    loss_term_weight: 0.77  # 1/1.3
    type: Weighted_Smooth_l1_Loss
    weights: [ 1.0, 0.3 ]

optimizer_cfg:
  solver: Adam
  lr: 0.0001
  betas: [ 0.9, 0.999 ]

scheduler_cfg:
  scheduler: MultiStepLR
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 14000

  warmup:
    type: LinearWarmup
    warmup_period: 500

trainer_cfg:
  save_name: CoExNet_SceneFlow
  restore_hint: 0
  restore_ckpt_strict: true
  log_iter: 10
  with_test: true
  enable_float16: false
  save_iter: 2000
  sync_BN: false
  total_iter: 20000
  total_epoch: 12
  optimizer_reset: false
  scheduler_reset: false
#  clip_grad_norm:
#    max_norm: 35
#    norm_type: 2
  sampler:
    batch_shuffle: true
    batch_size: 16


evaluator_cfg:
  save_name: CoExNet_SceneFlow
  eval_func: OpenStereoEvaluator
  restore_hint: 11000
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  enable_float16: false
  restore_ckpt_strict: true
  show_progress_bar: true
  sampler:
    batch_shuffle: false
    batch_size: 10
