data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/sceneflow/sceneflow_cleanpass_train.txt
  val_list: datasets/sceneflow/sceneflow_cleanpass_test.txt
  test_list: datasets/sceneflow/sceneflow_cleanpass_test.txt
  num_workers: 8
  train_batch_size: 32
  val_batch_size: 10
  pin_memory: false
  train_shuffle: true
  val_shuffle: false

  batch_uniform: false
  #  random_type: range
  #  w_range: [ 0.5, 2.0 ]
  #  h_range: [ 0.5, 2.0 ]
  #  random_type: choice
  #  h_range: [ 256, 288, 320, 352 ]
  #  w_range: [ 480, 512, 544, 576 ]

  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      #- type: RandomHorizontalFlip
      #  prob: 0.5
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: StereoPad
        size: [ 540, 960 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: CoExNet
  find_unused_parameters: true

  base_config:
    max_disp: 192


loss_cfg:
  - log_prefix: disp
    loss_term_weight: 0.77  # 1/1.3
    type: Weighted_Smooth_l1_Loss
    weights: [ 1.0, 0.3 ]


trainer_cfg:
  save_name: CoExNet_SceneFlow
  sync_bn: true
  fp16: true
  restore_hint: 0
  log_iter: 10

  optimizer_cfg:
    solver: Adam
    lr: 0.001
    betas: [ 0.9, 0.999 ]

  scheduler_cfg:
    scheduler: MultiStepLR
    gamma: 0.1
    milestones: [ 7, 12 ]
    warmup:
      warmup_steps: 100

  evaluator_cfg:
    metric:
      - d1_all
      - epe
      - thres_1
      - thres_2
      - thres_3

  clip_grad_cfg:
    type: norm
    max_norm: 35
    norm_type: 2
    # type: value
    # clip_value: 0.1



#  save_name: CoExNet_SceneFlow
#  restore_hint: 0
#  restore_ckpt_strict: true
#  log_iter: 10
#  with_test: true
#  enable_float16: true
#  save_iter: 1000
#  sync_BN: true
#  total_iter: 20000
#  total_epoch: 15
#  optimizer_reset: false
#  scheduler_reset: false
#  clip_grad_norm:
#    max_norm: 35
#    norm_type: 2
#  sampler:
#    batch_shuffle: true
#    batch_size: 4
#
#
#evaluator_cfg:
#  save_name: CoExNet_SceneFlow
#  eval_func: OpenStereoEvaluator
#  restore_hint: 0
#  metric:
#    - d1_all
#    - epe
#    - thres_1
#    - thres_2
#    - thres_3
#  enable_float16: true
#  restore_ckpt_strict: true
#  show_progress_bar: false
#  sampler:
#    batch_shuffle: false
#    batch_size: 1

