data_cfg:
  name: SceneFlow
  name: DrivingStereo
  root: data/DrivingStereo
  train_list: datasets/DrivingStereo/driving_stereo_phigent_train.txt
  val_list: datasets/DrivingStereo/driving_stereo_phigent_test.txt
  test_list: datasets/DrivingStereo/driving_stereo_phigent_test.txt
  num_workers: 8
  train_batch_size: 16
  val_batch_size: 10
  pin_memory: true
  shuffle: true

  batch_uniform: false

  transform:
    train:
      - type: RandomCrop
        size: [ 384, 768 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: StereoPad
        size: [ 576, 960 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: ACVNet

  base_config:
    max_disp: 192
    attn_weights_only: False
    freeze_attn_weights: False


loss_cfg:
  - log_prefix: disp
    loss_term_weight: 0.77  # 1/1.3
    type: Weighted_Smooth_l1_Loss
    weights: [ 1.0, 0.3 ]


trainer_cfg:
  save_name: ACVNet_ds
  total_epoch: 1000
  restore_hint: '/mnt/cfs/algorithm/yiqun.duan/stereo/openstereo/output/SceneFlow/ACVNet/ACVNet_SceneFlow_new/checkpoints/ACVNet_SceneFlow_new_epoch_050.pt'
  resume: false
  optimizer_reset: true
  scheduler_reset: true
  warmup_reset: true
  log_iter: 1 # iter
  save_every: 50 # epoch
  val_every: 10 # epoch
  amp: true
  sync_bn: true
  fix_bn: false
  init_parameters: false

  optimizer_cfg:
    solver: RMSprop
    lr: 0.001

  scheduler_cfg:
    scheduler: MultiStepLR
    gamma: 0.1
    milestones: [ 500, 800, 900 ]
    warmup:
      warmup_steps: 100

  evaluator_cfg:
    metric:
      - d1_all
      - epe
      - thres_1
      - thres_2
      - thres_3

  clip_grad_cfg:
    type: norm
    max_norm: 35
    norm_type: 2


