data_cfg:
  name: KITTI2012
  root: data/kitti12
  train_list: data/kitti12/train.txt
  test_list: data/kitti12/test.txt
  num_workers: 4

#  transform:
#    - type: RandomCrop
#      size: [384, 1248]
#    - type: RandomHorizontalFlip
#    - type: ToTensor
#    - type: Normalize
#      mean: [0.485, 0.456, 0.406]
#      std: [0.229, 0.224, 0.225]


model_cfg:
  model: GwcNet

  base_config:
    max_disp: 80
    downsample: 4
    num_groups: 40
    use_concat_volume: True
    concat_channels: 12

  # Backbone
  backbone_cfg:
    type: GwcNet

  # VolumeCostProcessor
  cost_processor_cfg:
    type: GwcVolumeCostProcessor

  # DispProcessor
  disp_processor_cfg:
    type: GwcDispProcessor

optimizer_cfg:
  solver: Adam
  lr: 0.001
  weight_decay: 0.0005


loss_cfg:
  type: Weighted_Smooth_l1_Loss

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 20000
    - 40000
  scheduler: MultiStepLR


trainer_cfg:
  enable_float16: False
  fix_BN: false
  log_iter: 10
  with_test: true
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: GwcNet_kitti12
  sync_BN: true
  total_iter: 60000

  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 2
  #    frames_num_fixed: 30
  #    frames_num_max: 50
  #    frames_num_min: 25
  #    sample_type: fixed_unordered

  transform:
    - img_w: 64
      type: BaseSilCuttingTransform


evaluator_cfg:
  enable_float16: False
  fix_BN: false
  restore_ckpt_strict: true
  restore_hint: 0
  sync_BN: true

  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 2
  #      - 8
  #      - 16
  #    frames_num_fixed: 30
  #    frames_num_max: 50
  #    frames_num_min: 25
  #    sample_type: fixed_unordered

  transform:
    - img_w: 64
      type: BaseSilCuttingTransform
