data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/sceneflow/sceneflow_finalpass_train.txt
  val_list: datasets/sceneflow/sceneflow_finalpass_test.txt
  test_list: datasets/sceneflow/sceneflow_finalpass_test.txt
  num_workers: 4

  batch_uniform: false
  #  random_type: range
  #  w_range: [ 0.5, 2.0 ]
  #  h_range: [ 0.5, 2.0 ]
  #  random_type: choice
  #  h_range: [ 256, 288, 320, 352 ]
  #  w_range: [ 480, 512, 544, 576 ]

  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      #- type: RandomHorizontalFlip
      #  prob: 0.5
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: TestCrop
        size: [ 512, 960 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: GwcNet
  find_unused_parameters: false

  base_config:
    max_disp: 192

  # Backbone
  backbone_cfg:
    type: GwcNet

  # VolumeCostProcessor
  cost_processor_cfg:
    type: GwcVolumeCostProcessor

  # DispProcessor
  disp_processor_cfg:
    type: GwcDispProcessor


loss_cfg:
  - log_prefix: disp
    type: Weighted_Smooth_l1_Loss
    loss_term_weight: 1
    weights: [ 0.5,0.5,0.7,1.0 ]


optimizer_cfg:
  solver: Adam
  lr: 0.001


scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 5000
    - 15000
  scheduler: MultiStepLR


trainer_cfg:
  save_name: GwcNet_SceneFlow
  enable_float16: false
  log_iter: 1
  with_test: true
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 100
  sync_BN: true
  fix_BN: false
  total_iter: 20000
  total_epoch: 30

  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 2


evaluator_cfg:
  eval_func: OpenStereoEvaluator
  save_name: GwcNet_SceneFlow
  restore_hint: 0
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3

  enable_float16: false
  restore_ckpt_strict: true
  show_progress_bar: false

  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 1
