data_cfg:
  name: KITTI2015
  root: data/kitti15
  train_list: datasets/KITTI15/kitti15_train200.txt
  val_list: datasets/KITTI15/kitti15_train200.txt
  test_list: datasets/KITTI15/kitti15_test.txt
#  name: KITTI2012
#  root: data/kitti12
#  train_list: datasets/KITTI12/kitti12_train194.txt
#  val_list: datasets/KITTI12/kitti12_train194.txt
#  test_list: datasets/KITTI12/kitti12_test.txt
  num_workers: 8
  train_batch_size: 4
  val_batch_size: 4
  pin_memory: true
  shuffle: true
  batch_uniform: false
  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    val:
      # - type: StereoPad
      - type: CropOrPad
        size: [ 384, 1248 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]

model_cfg:
  model: ACVNet
  small_model: False
  find_unused_parameters: true

  base_config:
    max_disp: 192
    attn_weights_only: False
    freeze_attn_weights: False


loss_cfg:
  type: ACVLoss # user defined loss


trainer_cfg:
  save_name: ACVNet_SceneFlow
  total_epoch: 192
  restore_hint: 128
  resume: true
  optimizer_reset: true
  scheduler_reset: true
  warmup_reset: true
  log_iter: 50 # iter
  save_every: 1 # epoch
  val_every: 1 # epoch
  amp: true
  sync_bn: false
  fix_bn: false
  init_parameters: false

  optimizer_cfg:
    solver: Adam
    lr: 0.001
    betas: [ 0.9, 0.999 ]

  scheduler_cfg:
    scheduler: MultiStepLR
    gamma: 0.5
    milestones: [ 20, 32, 40, 48, 56 ]
    warmup:
      warmup_steps: 100

  evaluator_cfg:
    metric:
      - d1_all
      - epe
      - bad_1
      - bad_2
      - bad_3

  clip_grad_cfg:
    #    type: norm
    #    max_norm: 35
    #    norm_type: 2
    type: value
    clip_value: 0.1
    
