data_cfg:
  name: DrivingStereo
  root: data/DrivingStereo
  train_list: datasets/DrivingStereo/driving_stereo_phigent_train.txt
  val_list: datasets/DrivingStereo/driving_stereo_phigent_test.txt
  test_list: datasets/DrivingStereo/driving_stereo_phigent_test.txt
  num_workers: 4
  train_batch_size: 8
  val_batch_size: 1
  pin_memory: true
  shuffle: true

  batch_uniform: false
  #  random_type: range
  #  w_range: [ 0.5, 2.0 ]
  #  h_range: [ 0.5, 2.0 ]
  #  random_type: choice
  #  h_range: [ 256, 288, 320, 352 ]
  #  w_range: [ 480, 512, 544, 576 ]

  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      #- type: RandomHorizontalFlip
      #  prob: 0.5
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    val:
      - type: CropOrPad
        size: [ 400, 880 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: CasStereoNet
  model_type: psmnet

  base_config:
    max_disp: 192


loss_cfg:
  type: CasStereoLoss # user defined loss


trainer_cfg:
  save_name: CasNet_DrivingStereo
  total_epoch: 10
  restore_hint: './output/SceneFlow/CasNet/CasNet_SceneFlow/checkpoints/CasNet_PSM_SceneFlow_epoch_020.pt'
  resume: false
  optimizer_reset: true
  scheduler_reset: true
  warmup_reset: false
  log_iter: 50 # iter
  save_every: 1 # epoch
  val_every: 1 # epoch
  amp: true
  sync_bn: false
  fix_bn: false
  init_parameters: false

  optimizer_cfg:
    solver: RMSprop
    lr: 0.001

  scheduler_cfg:
    scheduler: MultiStepLR
    gamma: 0.1
    milestones: [ 7 ]
    warmup:
      warmup_steps: 100

  evaluator_cfg:
    metric:
      - d1_all
      - epe
      - thres_1
      - thres_2
      - thres_3

  clip_grad_cfg:
    type: norm
    max_norm: 35
    norm_type: 2