data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/sceneflow/sceneflow_train.txt
  val_list: datasets/sceneflow/sceneflow_test.txt
  test_list: datasets/sceneflow/sceneflow_test.txt
  num_workers: 4

  transform:
    train:
      size: [ 256, 512 ] # random crop size
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]
    test:
      size: [ 512, 960 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: CasStereoNet

  base_config:
    max_disp: 192

#  # Backbone
#  backbone_cfg:
#    type: GwcNet
#
#  # VolumeCostProcessor
#  cost_processor_cfg:
#    type: GwcVolumeCostProcessor
#
#  # DispProcessor
#  disp_processor_cfg:
#    type: GwcDispProcessor


optimizer_cfg:
  solver: AdamW
  lr: 0.001
  betas: [ 0.9, 0.999 ]


loss_cfg:
  type: CasStereoLoss # user defined loss

scheduler_cfg:
  scheduler: MultiStepLR
  gamma: 0.5
  milestones:
    - 75000
    - 90000
    - 105000
    - 120000


trainer_cfg:
  save_name: CasNet_SceneFlow
  restore_hint: weights/CasNet_SceneFlow-03000.pt
  restore_ckpt_strict: true
  log_iter: 1
  with_test: true
  enable_float16: false
#  sync_BN: true
  save_iter: 200
  total_iter: 150000
  total_epoch: 20
  optimizer_reset: false
  scheduler_reset: false

  sampler:
    # type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 2


evaluator_cfg:
  eval_func: OpenStereoEvaluator
  save_name: CasNet_SceneFlow
  restore_hint: weights/CasNet_SceneFlow-03000.pt
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  restore_ckpt_strict: true
  enable_float16: false

  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 1
